function lidarSensor = createLidarSensor(cfg, scenario, egoVehicle)
lidarSensor = lidarPointCloudGenerator( ...
    'SensorIndex', 1, ...
    'SensorLocation', [0 0], ...        % centered on the ego actor's own xy
    'Height', cfg.lidar.position(3), ...
    'MaxRange', cfg.lidar.range, ...
    'AzimuthResolution', cfg.lidar.azimuthResolution, ...
    'ElevationLimits', cfg.lidar.elevationLimits, ...
    'ElevationResolution', cfg.lidar.elevationResolution, ...
    'HasNoise', false, ...
    'HasOrganizedOutput', false);

lidarSensor.ActorProfiles     = actorProfiles(scenario);
lidarSensor.EgoVehicleActorID = egoVehicle.ActorID;
end
