function lidarSensor = createLidarSensor(cfg, scenario, egoVehicle)
lidarSensor = lidarPointCloudGenerator( ...
    'SensorIndex', 1, ...
    'MaxRange', cfg.lidar.range, ...
    'AzimuthResolution', cfg.lidar.azimuthResolution, ...
    'ElevationLimits', cfg.lidar.elevationLimits, ...
    'ElevationResolution', cfg.lidar.elevationResolution, ...
    'HasNoise', false, ...
    'HasOrganizedOutput', false);

lidarSensor.ActorProfiles      = actorProfiles(scenario);
lidarSensor.EgoVehicleActorID  = egoVehicle.ActorID;
end
