function displayScenario(cfg)

figure

hold on
grid on
axis equal

xlabel('X (m)')
ylabel('Y (m)')

title('Roadside Pedestrian Warning System')

%% Draw Road

plot(...
    cfg.road.centers(:,1),...
    cfg.road.centers(:,2),...
    'k',...
    'LineWidth',8)

%% Draw Building

rectangle(...
    'Position',...
    [...
        cfg.building.position(1),...
        cfg.building.position(2),...
        cfg.building.length,...
        cfg.building.width...
    ],...
    'FaceColor',[0.65 0.65 0.65],...
    'EdgeColor','k');

%% Draw Detection Zone

rectangle(...
    'Position',...
    [...
        cfg.detectionZone.x(1),...
        cfg.detectionZone.y(1),...
        diff(cfg.detectionZone.x),...
        diff(cfg.detectionZone.y)...
    ],...
    'EdgeColor','g',...
    'LineStyle','--',...
    'LineWidth',2);

%% Draw LiDAR

plot(...
    cfg.lidar.position(1),...
    cfg.lidar.position(2),...
    '^r',...
    'MarkerSize',12,...
    'MarkerFaceColor','r');

%% Draw Warning Sign

plot(...
    cfg.sign.position(1),...
    cfg.sign.position(2),...
    'sb',...
    'MarkerSize',10,...
    'MarkerFaceColor','b');

%% Labels

text(...
    cfg.lidar.position(1)+1,...
    cfg.lidar.position(2),...
    'LiDAR');

text(...
    cfg.sign.position(1)+1,...
    cfg.sign.position(2),...
    'Warning Sign');

text(...
    cfg.building.position(1)+2,...
    cfg.building.position(2)+2,...
    'Building');

text(...
    mean(cfg.detectionZone.x),...
    mean(cfg.detectionZone.y),...
    'Detection Zone',...
    'HorizontalAlignment','center');

end