function ped = createPedestrian(scenario, cfg)
%CREATEPEDESTRIAN Add the pedestrian actor and give it a trajectory.
% Ground-truth actor for this milestone -- no LiDAR involved yet.

ped = actor(scenario, ...
    'ClassID', 4, ...          % 4 = pedestrian in Automated Driving Toolbox
    'Length', 0.5, ...
    'Width',  0.5, ...
    'Height', 1.7, ...
    'Position', cfg.pedestrian.waypoints(1,:), ...
    'Name', 'Pedestrian');

% trajectory(ped, cfg.pedestrian.waypoints, cfg.pedestrian.speed);

end
