function ped = createPedestrian(scenario, cfg)
%CREATEPEDESTRIAN Real human mesh actor, position driven manually elsewhere.

ped = actor(scenario, ...
    'ClassID', 4, ...
    'Length', cfg.pedestrian.length, ...
    'Width',  cfg.pedestrian.width, ...
    'Height', cfg.pedestrian.height, ...
    'Position', cfg.pedestrian.waypoints(1,:), ...
    'Mesh', driving.scenario.pedestrianMesh, ...
    'Name', 'Pedestrian');

% NOTE: no trajectory()/smoothTrajectory() call here.
% Both fit a spline through the waypoints and round off corners.
% Position is instead driven manually, frame by frame, in main3D.m using
% positionAlongPath() -- true piecewise-linear motion, sharp vertices.
end
